---
output: html_document
runtime: shiny
---
# Salivary gland tumor genetics project

### Git control
Open the shell.  
git push -u origin master  
and login the git.  

### Data load
```{r}

Saliva <- read.csv("~/Documents/R/Salivary/Saliva_TERT_pik3ca.csv")
```

### loading librarys
```{r echo=FALSE}
require("ggplot2", lib.loc="/Library/Frameworks/R.framework/Versions/3.2/Resources/library")
require("moonBook", lib.loc="/Library/Frameworks/R.framework/Versions/3.2/Resources/library")
require("ztable", lib.loc="/Library/Frameworks/R.framework/Versions/3.2/Resources/library")
```


### Data summary
```{r echo=FALSE}
summary(Saliva)
```

### ploting size vs telomere lengh , histology group
```{r echo=FALSE}
Saliva$hist_group<-factor(Saliva$hist_group, levels=c(1,2,3,4), labels = c("pleomorphic adenoma", "warthin", "carcinoma", "etc"))
Saliva$sex <- factor(Saliva$sex, levels=c(1,2), labels = c("male", "female"))
qplot(size, telomere_length, data=Saliva, shape=hist_group, ylim = 40)

```

### ploting size vs PIK3CA expression , histology group
```{r echo=FALSE}
qplot(size, PIK3CA_amp, data=Saliva, shape=hist_group)
```

### Sex table
```{r echo=FALSE}

sexvar<-c("sex", "age", "location", "hist_group","size" )
Saliva_table<-Saliva[sexvar]
# res_sex= mytable(sex~.,data=Saliva_table)
# ztable(res_sex)
mytable(sex~.,data=Saliva_table)
```

### Histology table
```{r echo=FALSE}
#res_hist= mytable(hist_group~., data=Saliva_table)
#ztable(res_hist)
mytable(hist_group~., data=Saliva_table)
```

### Histology based seletion
```{r echo=FALSE}
Saliva_3 <- subset(Saliva, hist_group != "etc")
Saliva_3_table <- Saliva_3[sexvar]
#res_sex_3= mytable(sex~.,data=Saliva_3_table)
#ztable(res_sex_3)
#res_hist_3= mytable(hist_group~., data=Saliva_3_table)
#ztable(res_hist_3)
mytable(sex~.,data=Saliva_3_table)
mytable(hist_group~., data=Saliva_3_table)
```

### Box plot
```{r echo=FALSE}
Saliva_3_TL <- subset(Saliva_3, telomere_length<40)
qplot(hist_group, telomere_length, data=Saliva_3_TL, geom=c("boxplot", "jitter"), fill=hist_group)
qplot(hist_group, PIK3CA_amp, data=Saliva_3, geom=c("boxplot", "jitter"), fill=hist_group)
Saliva_3_MT <- subset(Saliva_3, MT_copynumber<100)
qplot(hist_group, MT_copynumber, data=Saliva_3_MT, geom=c("boxplot", "jitter"), fill=hist_group)
```
